export type SampleAlgorithm = {
  id: string;
  name: string;
  category: string;
  complexity: string;
  summary: string;
};

/**
 * 仮データ(プレースホルダ)。有名なものからマニアックなものまで幅広く収録。
 * 実データ・状態遷移ロジック・AST解析による複雑度判定の実装は今後のフェーズ(docs/design/ui-design.md 7節)。
 */
export const CATEGORY_ORDER = [
  "ソート",
  "探索",
  "グラフ",
  "動的計画法",
  "貪欲法",
  "文字列",
  "データ構造",
  "数論・暗号",
  "計算幾何",
  "最適化・確率的手法",
  "情報検索・ランキング",
  "機械学習",
  "デザインパターン",
  "シミュレーション・群知能",
  "分散システム",
] as const;

export const sampleAlgorithms: SampleAlgorithm[] = [
  // ソート
  {
    id: "bubble-sort",
    name: "バブルソート",
    category: "ソート",
    complexity: "O(n²)",
    summary:
      "隣接要素の比較・交換を繰り返す最も素朴な手法。仕組みの理解に最適だが実務での採用は少ない。",
  },
  {
    id: "selection-sort",
    name: "選択ソート",
    category: "ソート",
    complexity: "O(n²)",
    summary: "未整列部分から最小値を選んで確定させていく。交換回数が少なく書き込みコストが高い場面で有利。",
  },
  {
    id: "insertion-sort",
    name: "挿入ソート",
    category: "ソート",
    complexity: "O(n²)",
    summary: "整列済み部分に1つずつ挿入していく。ほぼ整列済みのデータに対しては高速に動く。",
  },
  {
    id: "merge-sort",
    name: "マージソート",
    category: "ソート",
    complexity: "O(n log n)",
    summary: "分割統治+マージで安定ソートを実現する。外部ソートや並列化と相性が良い。",
  },
  {
    id: "quick-sort",
    name: "クイックソート",
    category: "ソート",
    complexity: "O(n log n)",
    summary: "ピボットを軸に分割統治する。平均は非常に高速だが、ピボット選択次第で最悪ケースに落ち込む。",
  },
  {
    id: "heap-sort",
    name: "ヒープソート",
    category: "ソート",
    complexity: "O(n log n)",
    summary: "二分ヒープを使い、追加メモリなしで整列できる。安定性はないが最悪ケースも保証される。",
  },
  {
    id: "shell-sort",
    name: "シェルソート",
    category: "ソート",
    complexity: "O(n log n) 〜 O(n²)",
    summary: "挿入ソートを間隔を空けて繰り返し適用し、徐々に間隔を詰めていく改良版。",
  },
  {
    id: "counting-sort",
    name: "計数ソート(カウンティングソート)",
    category: "ソート",
    complexity: "O(n + k)",
    summary: "値の出現回数を数えて並べる。値域が小さい整数データに強い非比較ソート。",
  },
  {
    id: "radix-sort",
    name: "基数ソート",
    category: "ソート",
    complexity: "O(d(n + k))",
    summary: "桁ごとに安定ソートを繰り返す。整数や固定長文字列の整列に向く。",
  },
  {
    id: "bucket-sort",
    name: "バケットソート",
    category: "ソート",
    complexity: "O(n + k)",
    summary: "値域をバケットに分けて個別に整列する。一様分布のデータで威力を発揮する。",
  },
  {
    id: "tim-sort",
    name: "Timsort",
    category: "ソート",
    complexity: "O(n log n)",
    summary: "挿入ソートとマージソートを組み合わせた実用重視のハイブリッド。Python/Javaの標準ソートに採用。",
  },
  {
    id: "cocktail-sort",
    name: "カクテルシェイカーソート",
    category: "ソート",
    complexity: "O(n²)",
    summary: "バブルソートを双方向に行う改良版。両端から交換していくことで偏った未整列要素の移動を速める。",
  },
  {
    id: "comb-sort",
    name: "コムソート",
    category: "ソート",
    complexity: "O(n log n)(平均)",
    summary:
      "間隔を1.3倍ずつ縮めながらバブルソートを行い、小さい値が末尾に残る「亀」問題を解消する。",
  },
  {
    id: "pancake-sort",
    name: "パンケーキソート",
    category: "ソート",
    complexity: "O(n²)",
    summary:
      "先頭からのひっくり返し操作だけで整列する。比較よりも「操作回数」の最小化という制約付き設定のおもしろさが本質。",
  },
  {
    id: "cycle-sort",
    name: "サイクルソート",
    category: "ソート",
    complexity: "O(n²)",
    summary: "書き込み回数を理論上の最小(各要素1回)に抑える、書き込みコストが高い記憶媒体向けの特殊ソート。",
  },
  {
    id: "intro-sort",
    name: "イントロソート(Introsort)",
    category: "ソート",
    complexity: "O(n log n)",
    summary:
      "クイックソートを基本にしつつ再帰が深くなるとヒープソートに切り替える実用重視のハイブリッド。C++標準ライブラリのstd::sortに採用。",
  },
  {
    id: "bogosort",
    name: "ボゴソート",
    category: "ソート",
    complexity: "O((n+1)!)(期待値)",
    summary:
      "ランダムに並べ替えて整列済みか確認するだけを繰り返す。実用性はほぼゼロだが、他のソートがなぜ工夫されているのかを逆説的に教えてくれる。",
  },

  // 探索
  {
    id: "linear-search",
    name: "線形探索",
    category: "探索",
    complexity: "O(n)",
    summary: "先頭から順に調べる最も単純な探索。前処理不要でどんなデータにも使える。",
  },
  {
    id: "binary-search",
    name: "二分探索",
    category: "探索",
    complexity: "O(log n)",
    summary: "ソート済み配列を半分ずつ絞り込みながら目的の値を探す。前提条件(整列済み)が鍵。",
  },
  {
    id: "ternary-search",
    name: "三分探索",
    category: "探索",
    complexity: "O(log n)",
    summary: "単峰関数の極値探索に使う、二分探索の派生形。",
  },
  {
    id: "bfs",
    name: "幅優先探索(BFS)",
    category: "探索",
    complexity: "O(V + E)",
    summary: "近い頂点から順に探索し、重みなしグラフでの最短経路を保証する。",
  },
  {
    id: "dfs",
    name: "深さ優先探索(DFS)",
    category: "探索",
    complexity: "O(V + E)",
    summary: "行き止まりまで掘り進めてから戻る。経路の全探索や連結成分の検出に使う。",
  },
  {
    id: "a-star",
    name: "A*探索",
    category: "探索",
    complexity: "O(E)",
    summary: "ヒューリスティックで探索方向を絞り込むダイクストラ法の拡張。ゲームの経路探索の定番。",
  },
  {
    id: "iddfs",
    name: "反復深化探索(IDDFS)",
    category: "探索",
    complexity: "O(b^d)",
    summary: "深さ制限を徐々に広げるDFS。メモリ効率とBFS相当の最短性を両立する。",
  },
  {
    id: "jump-search",
    name: "ジャンプ探索",
    category: "探索",
    complexity: "O(√n)",
    summary: "一定間隔で飛び飛びに調べてから線形探索する。ジャンプコストが低い環境で二分探索より有利な場合がある。",
  },
  {
    id: "exponential-search",
    name: "指数探索",
    category: "探索",
    complexity: "O(log n)",
    summary: "範囲を倍々に広げて対象区間を見つけてから二分探索する。先頭に値が集中する無限長データに強い。",
  },
  {
    id: "interpolation-search",
    name: "補間探索",
    category: "探索",
    complexity: "O(log log n)(平均)",
    summary: "値の分布から位置を推定してジャンプする。一様分布データでは二分探索より高速に収束する。",
  },
  {
    id: "fibonacci-search",
    name: "フィボナッチ探索",
    category: "探索",
    complexity: "O(log n)",
    summary: "フィボナッチ数列の比率で分割点を決める、除算を使わずに実装できる二分探索の派生形。",
  },

  // グラフ
  {
    id: "dijkstra",
    name: "ダイクストラ法",
    category: "グラフ",
    complexity: "O((V + E) log V)",
    summary: "重み付きグラフの最短経路を、確定済み頂点を1つずつ広げながら求める。負の辺には非対応。",
  },
  {
    id: "bellman-ford",
    name: "ベルマン・フォード法",
    category: "グラフ",
    complexity: "O(VE)",
    summary: "負の辺を許容する最短経路法。負閉路の検出にも使える。",
  },
  {
    id: "floyd-warshall",
    name: "フロイド・ワーシャル法",
    category: "グラフ",
    complexity: "O(V³)",
    summary: "全点対の最短経路を動的計画法で一括に求める。",
  },
  {
    id: "prim",
    name: "プリム法",
    category: "グラフ",
    complexity: "O(E log V)",
    summary: "頂点を1つずつ広げながら最小全域木を構築する。",
  },
  {
    id: "kruskal",
    name: "クラスカル法",
    category: "グラフ",
    complexity: "O(E log E)",
    summary: "辺をコストの小さい順に採用し、Union-Findで閉路を避けながら最小全域木を作る。",
  },
  {
    id: "topological-sort",
    name: "トポロジカルソート",
    category: "グラフ",
    complexity: "O(V + E)",
    summary: "依存関係のあるタスクを実行可能な順序に並べる。DAG(有向非巡回グラフ)にのみ適用できる。",
  },
  {
    id: "tarjan-scc",
    name: "タージャンの強連結成分分解",
    category: "グラフ",
    complexity: "O(V + E)",
    summary: "1回のDFSで有向グラフの強連結成分をすべて求める。",
  },
  {
    id: "union-find",
    name: "Union-Find(素集合データ構造)",
    category: "グラフ",
    complexity: "O(α(n))(ほぼ定数)",
    summary: "グループの併合と所属判定をほぼ定数時間で行う。クラスカル法の内部でも活躍する。",
  },
  {
    id: "ford-fulkerson",
    name: "フォード・ファルカーソン法",
    category: "グラフ",
    complexity: "O(E・maxflow)",
    summary: "増加パスを探し続けて最大フローを求める。増加パスの選び方で性能が大きく変わる。",
  },
  {
    id: "edmonds-karp",
    name: "エドモンズ・カープ法",
    category: "グラフ",
    complexity: "O(VE²)",
    summary: "フォード・ファルカーソン法の増加パスをBFSで選ぶことで計算量を保証した版。",
  },
  {
    id: "hopcroft-karp",
    name: "ホップクロフト・カープ法",
    category: "グラフ",
    complexity: "O(E√V)",
    summary: "二部グラフの最大マッチングを高速に求める。",
  },
  {
    id: "johnson",
    name: "ジョンソンのアルゴリズム",
    category: "グラフ",
    complexity: "O(V² log V + VE)",
    summary: "負の辺を再重み付けしてから全点対最短経路を高速に解く。",
  },
  {
    id: "dinic",
    name: "ディニッツ法",
    category: "グラフ",
    complexity: "O(V²E)",
    summary: "レベルグラフとブロッキングフローを使い、最大フローを高速に求める。",
  },
  {
    id: "kahn",
    name: "カーンのアルゴリズム(トポロジカルソート)",
    category: "グラフ",
    complexity: "O(V + E)",
    summary: "入次数0の頂点から順に取り除いていく、DFSを使わないトポロジカルソートの実装。",
  },
  {
    id: "boruvka",
    name: "ボルーフカ法",
    category: "グラフ",
    complexity: "O(E log V)",
    summary: "各連結成分から最も安い辺を同時に選び続ける、並列化しやすい最小全域木アルゴリズム。",
  },
  {
    id: "floyd-cycle-detection",
    name: "フロイドの循環検出法(Tortoise and Hare)",
    category: "グラフ",
    complexity: "O(n)",
    summary: "遅いポインタと速いポインタを使い、追加メモリなしで連結リストやシーケンスの循環を検出する。",
  },

  // 動的計画法
  {
    id: "knapsack-dp",
    name: "0-1ナップサック問題",
    category: "動的計画法",
    complexity: "O(nW)",
    summary: "部分問題の解を表に記録し、重複計算を避けながら最適な詰め方を組み立てる。",
  },
  {
    id: "lcs",
    name: "最長共通部分列(LCS)",
    category: "動的計画法",
    complexity: "O(nm)",
    summary: "2つの列に共通する最長の並びを求める。差分表示(diff)の基礎理論。",
  },
  {
    id: "lis",
    name: "最長増加部分列(LIS)",
    category: "動的計画法",
    complexity: "O(n log n)",
    summary: "二分探索を併用することで、素朴なO(n²)から高速化できる典型例。",
  },
  {
    id: "edit-distance",
    name: "編集距離(レーベンシュタイン距離)",
    category: "動的計画法",
    complexity: "O(nm)",
    summary: "挿入・削除・置換の最小回数で2つの文字列の近さを測る。",
  },
  {
    id: "matrix-chain-multiplication",
    name: "行列連鎖積(区間DP)",
    category: "動的計画法",
    complexity: "O(n³)",
    summary: "行列の掛け算の順序を工夫することで、総計算量を最小化する。",
  },
  {
    id: "tsp-bitdp",
    name: "巡回セールスマン問題(ビットDP)",
    category: "動的計画法",
    complexity: "O(2ⁿ・n²)",
    summary: "訪問済み集合をビットで表現し状態数を抑える、古典的なDP高速化テクニック。",
  },
  {
    id: "coin-change",
    name: "硬貨交換問題(コインチェンジ)",
    category: "動的計画法",
    complexity: "O(nW)",
    summary: "目的金額を作る最小枚数(または組み合わせ数)を、部分問題の再利用で求める。",
  },
  {
    id: "longest-palindromic-subsequence",
    name: "最長回文部分列",
    category: "動的計画法",
    complexity: "O(n²)",
    summary: "文字列を反転したものとのLCSとして解ける、DPの応用力を示す好例。",
  },
  {
    id: "egg-drop",
    name: "卵割り問題(Egg Drop Puzzle)",
    category: "動的計画法",
    complexity: "O(n・k²)(素朴な実装)",
    summary: "割れる階数を最小の試行回数で特定する、最悪ケース最適化の古典的DP。",
  },
  {
    id: "rod-cutting",
    name: "棒の切断問題(Rod Cutting)",
    category: "動的計画法",
    complexity: "O(n²)",
    summary: "棒をどう切り分ければ売却額を最大化できるかを、部分問題の組み合わせで求める。",
  },
  {
    id: "subset-sum",
    name: "部分和問題(Subset Sum)",
    category: "動的計画法",
    complexity: "O(nW)",
    summary: "与えられた集合から和が目標値になる部分集合が存在するかを判定する、ナップサック問題の姉妹形。",
  },

  // 貪欲法
  {
    id: "huffman-coding",
    name: "ハフマン符号化",
    category: "貪欲法",
    complexity: "O(n log n)",
    summary: "出現頻度の低い記号ほど長い符号を割り当て、全体の符号長を最小化する。",
  },
  {
    id: "interval-scheduling",
    name: "区間スケジューリング問題",
    category: "貪欲法",
    complexity: "O(n log n)",
    summary: "終了時刻の早い順に選ぶ貪欲法で、両立可能な区間の最大数を求められることを証明できる好例。",
  },
  {
    id: "kadane",
    name: "カダンのアルゴリズム(最大部分配列問題)",
    category: "貪欲法",
    complexity: "O(n)",
    summary: "局所最適な部分和を更新し続けるだけで全体最適に到達する、貪欲法とDPの境界にある手法。",
  },

  // 文字列
  {
    id: "kmp",
    name: "KMP法(Knuth-Morris-Pratt法)",
    category: "文字列",
    complexity: "O(n + m)",
    summary: "不一致時に照合済み情報を使い、パターンを後戻りさせずに文字列検索する。",
  },
  {
    id: "boyer-moore",
    name: "Boyer-Moore法",
    category: "文字列",
    complexity: "O(n/m) 〜 O(nm)",
    summary: "パターンの末尾から比較し、大きくスキップすることで実用上高速な文字列検索を実現する。",
  },
  {
    id: "rabin-karp",
    name: "Rabin-Karp法",
    category: "文字列",
    complexity: "O(n + m)",
    summary: "ハッシュ値の比較で候補を絞り込む文字列検索。複数パターンの同時検索に強い。",
  },
  {
    id: "z-algorithm",
    name: "Z algorithm",
    category: "文字列",
    complexity: "O(n)",
    summary: "各位置から始まる接頭辞との一致長を、線形時間ですべて求める。",
  },
  {
    id: "manacher",
    name: "Manacherのアルゴリズム",
    category: "文字列",
    complexity: "O(n)",
    summary: "すべての中心について最長回文半径を線形時間で求める。",
  },
  {
    id: "aho-corasick",
    name: "Aho-Corasick法",
    category: "文字列",
    complexity: "O(n + m + z)",
    summary: "複数パターンを1本のオートマトンにまとめ、テキストを1回走査するだけで全パターンを検出する。",
  },
  {
    id: "suffix-array",
    name: "接尾辞配列(Suffix Array)",
    category: "文字列",
    complexity: "O(n log n)",
    summary: "全ての接尾辞をソートした配列。文字列検索や最長共通部分文字列の土台になる。",
  },
  {
    id: "longest-common-substring",
    name: "最長共通部分文字列",
    category: "文字列",
    complexity: "O(n + m)",
    summary: "接尾辞配列や接尾辞木を使うことで、2つの文字列に連続して共通する部分を高速に見つける。",
  },
  {
    id: "suffix-automaton",
    name: "接尾辞オートマトン",
    category: "文字列",
    complexity: "O(n)",
    summary: "全ての部分文字列の出現を線形サイズのオートマトンで表現する、文字列処理の圧縮表現。",
  },
  {
    id: "burrows-wheeler-transform",
    name: "Burrows-Wheeler変換(BWT)",
    category: "文字列",
    complexity: "O(n log n)",
    summary: "文字列を可逆的に並べ替えて同じ文字を隣接させ、圧縮しやすい形に変換する。bzip2の中核技術。",
  },
  {
    id: "run-length-encoding",
    name: "ランレングス符号化(RLE)",
    category: "文字列",
    complexity: "O(n)",
    summary: "同じ値の連続をその値と回数の組に置き換える、最も単純な可逆圧縮。",
  },

  // データ構造
  {
    id: "binary-search-tree",
    name: "二分探索木",
    category: "データ構造",
    complexity: "O(log n) 〜 O(n)",
    summary: "左小右大の性質で探索・挿入・削除をこなす。偏ると性能が線形に劣化する弱点を持つ。",
  },
  {
    id: "red-black-tree",
    name: "赤黒木",
    category: "データ構造",
    complexity: "O(log n)",
    summary: "色と回転規則で自己平衡を保つ二分探索木。多くの言語の標準ライブラリの内部実装に採用されている。",
  },
  {
    id: "segment-tree",
    name: "セグメント木",
    category: "データ構造",
    complexity: "O(log n)",
    summary: "区間に対する演算(和・最小値など)を高速に更新・照会できる木構造。",
  },
  {
    id: "fenwick-tree",
    name: "フェニック木(Binary Indexed Tree)",
    category: "データ構造",
    complexity: "O(log n)",
    summary: "累積和の更新・照会を、セグメント木よりも省メモリ・省コードで実現する。",
  },
  {
    id: "trie",
    name: "トライ木",
    category: "データ構造",
    complexity: "O(文字数)",
    summary: "共通の接頭辞を共有して文字列集合を格納する木。前方一致検索や入力補完に向く。",
  },
  {
    id: "bloom-filter",
    name: "ブルームフィルタ",
    category: "データ構造",
    complexity: "O(k)",
    summary: "偽陽性を許容する代わりに、極めて省メモリで「集合に含まれるか」を判定する確率的データ構造。",
  },
  {
    id: "skip-list",
    name: "スキップリスト",
    category: "データ構造",
    complexity: "O(log n)(期待値)",
    summary: "複数階層のリンクリストで、平衡木に近い性能を乱数だけで実現する。",
  },
  {
    id: "lru-cache",
    name: "LRUキャッシュ",
    category: "データ構造",
    complexity: "O(1)",
    summary: "ハッシュマップと双方向リストを組み合わせ、最も使われていないデータを定数時間で追い出す。",
  },
  {
    id: "avl-tree",
    name: "AVL木",
    category: "データ構造",
    complexity: "O(log n)",
    summary: "左右の高さの差を1以内に保つことで自己平衡する、最初に発明された平衡二分探索木。",
  },
  {
    id: "b-tree",
    name: "B木",
    category: "データ構造",
    complexity: "O(log n)",
    summary: "1ノードに複数キーを持たせ木を浅く保つ。ディスクI/Oを最小化するためデータベースやファイルシステムで多用される。",
  },
  {
    id: "treap",
    name: "トリープ(Treap)",
    category: "データ構造",
    complexity: "O(log n)(期待値)",
    summary:
      "各ノードにランダムな優先度を持たせ、二分探索木の順序とヒープの優先度を同時に満たすことで平衡を確率的に保証する。",
  },
  {
    id: "splay-tree",
    name: "スプレー木",
    category: "データ構造",
    complexity: "O(log n)(償却)",
    summary: "アクセスしたノードを回転で根まで持ち上げる。局所性の高いアクセスパターンで特に高速。",
  },
  {
    id: "interval-tree",
    name: "区間木(Interval Tree)",
    category: "データ構造",
    complexity: "O(log n + k)",
    summary: "多数の区間の中から指定範囲と重なるものを高速に列挙する。",
  },
  {
    id: "kd-tree",
    name: "kd木",
    category: "データ構造",
    complexity: "O(log n)(平衡時)",
    summary: "多次元空間を軸ごとに分割する木構造。最近傍探索や範囲検索に使う。",
  },
  {
    id: "quad-tree",
    name: "四分木(Quadtree)",
    category: "データ構造",
    complexity: "O(log n)(平衡時)",
    summary: "2次元空間を4分割し続ける木構造。衝突判定や画像圧縮、地図タイルの管理に使う。",
  },
  {
    id: "sparse-table",
    name: "疎表(Sparse Table)",
    category: "データ構造",
    complexity: "O(1)(クエリ)",
    summary: "事前計算で区間最小値などのクエリを定数時間で答える、更新のないデータ向けの構造。",
  },

  // 数論・暗号
  {
    id: "euclidean-algorithm",
    name: "ユークリッドの互除法",
    category: "数論・暗号",
    complexity: "O(log min(a,b))",
    summary: "剰余を取り続けるだけで最大公約数を求める、現存する最古級のアルゴリズムの一つ。",
  },
  {
    id: "extended-euclidean",
    name: "拡張ユークリッドの互除法",
    category: "数論・暗号",
    complexity: "O(log min(a,b))",
    summary: "最大公約数に加え、ax + by = gcd(a,b) を満たす係数まで同時に求める。",
  },
  {
    id: "sieve-of-eratosthenes",
    name: "エラトステネスの篩",
    category: "数論・暗号",
    complexity: "O(n log log n)",
    summary: "合成数を篩い落としていくことで、ある範囲の素数を一括で列挙する。",
  },
  {
    id: "miller-rabin",
    name: "ミラー・ラビン素数判定法",
    category: "数論・暗号",
    complexity: "O(k log³ n)",
    summary: "確率的に大きな数の素数判定を行う。RSA暗号の鍵生成などで実用される。",
  },
  {
    id: "fft",
    name: "高速フーリエ変換(FFT)",
    category: "数論・暗号",
    complexity: "O(n log n)",
    summary: "多項式乗算や信号処理を、素朴なO(n²)から劇的に高速化する分割統治アルゴリズム。",
  },
  {
    id: "karatsuba",
    name: "カラツバ法",
    category: "数論・暗号",
    complexity: "O(n^1.585)",
    summary: "大きな数の掛け算を3回の乗算に分割統治することで、筆算より高速化する。",
  },
  {
    id: "rsa",
    name: "RSA暗号",
    category: "数論・暗号",
    complexity: "O(log n)(べき乗剰余)",
    summary: "素因数分解の困難さを安全性の根拠にした公開鍵暗号。べき乗剰余の高速計算が実装の要。",
  },
  {
    id: "modular-exponentiation",
    name: "高速べき乗(繰り返し二乗法)",
    category: "数論・暗号",
    complexity: "O(log n)",
    summary:
      "指数を2進展開して二乗を繰り返すことで、巨大な指数のべき乗剰余を高速に計算する。RSA等の暗号処理の基盤。",
  },
  {
    id: "chinese-remainder-theorem",
    name: "中国剰余定理(CRT)",
    category: "数論・暗号",
    complexity: "O(log n)",
    summary: "複数の合同式から元の値を復元する。RSA復号の高速化にも応用される。",
  },
  {
    id: "baby-step-giant-step",
    name: "Baby-step Giant-step法",
    category: "数論・暗号",
    complexity: "O(√n)",
    summary: "離散対数問題を、力任せのO(n)から時間・空間トレードオフでO(√n)に高速化する。",
  },
  {
    id: "pollards-rho",
    name: "ポラードのロー法",
    category: "数論・暗号",
    complexity: "O(n^(1/4))(期待値)",
    summary: "サイクル検出の考え方を応用し、大きな合成数の素因数を確率的に高速発見する。",
  },
  {
    id: "diffie-hellman",
    name: "ディフィー・ヘルマン鍵共有",
    category: "数論・暗号",
    complexity: "O(log n)(べき乗剰余)",
    summary: "離散対数問題の困難さを利用し、盗聴者がいる通信路上で共通鍵を安全に共有する。",
  },
  {
    id: "lucas-lehmer",
    name: "ルーカス・レーマー・テスト",
    category: "数論・暗号",
    complexity: "O(n²)(nビット数に対して)",
    summary: "メルセンヌ数専用の決定的素数判定法。史上最大級の素数発見に使われている。",
  },
  {
    id: "russian-peasant-multiplication",
    name: "ロシア農民の乗算法",
    category: "数論・暗号",
    complexity: "O(log n)",
    summary: "片方を半分に、もう片方を倍にしていくだけで掛け算を実現する、二進数表現の本質を体感できる古典技法。",
  },

  // 計算幾何
  {
    id: "graham-scan",
    name: "凸包(グラハムスキャン)",
    category: "計算幾何",
    complexity: "O(n log n)",
    summary: "点群を角度順にソートしてスタックで包んでいく、凸包を求める代表的手法。",
  },
  {
    id: "line-sweep-intersection",
    name: "線分交差判定(走査線法)",
    category: "計算幾何",
    complexity: "O(n log n)",
    summary: "平面を掃くように処理することで、素朴なO(n²)の全探索を避ける計算幾何の基本テクニック。",
  },
  {
    id: "closest-pair-of-points",
    name: "最近点対問題",
    category: "計算幾何",
    complexity: "O(n log n)",
    summary: "分割統治で候補を絞り込み、素朴なO(n²)の総当りを避けて最も近い2点を求める。",
  },
  {
    id: "delaunay-triangulation",
    name: "ドロネー三角形分割",
    category: "計算幾何",
    complexity: "O(n log n)",
    summary: "各三角形の外接円が他の点を含まないように点群を三角形分割する。地形モデリングやメッシュ生成の基礎。",
  },
  {
    id: "voronoi-diagram",
    name: "ボロノイ図",
    category: "計算幾何",
    complexity: "O(n log n)",
    summary: "各点に最も近い領域で平面を分割する。ドロネー三角形分割と双対の関係にある。",
  },
  {
    id: "rotating-calipers",
    name: "回転キャリパー法",
    category: "計算幾何",
    complexity: "O(n)",
    summary: "凸多角形の周りを2本の平行線で挟んで回転させ、最大幅や最小包含長方形などを求める。",
  },
  {
    id: "point-in-polygon",
    name: "点の内外判定(レイキャスティング法)",
    category: "計算幾何",
    complexity: "O(n)",
    summary: "点から伸ばした半直線が多角形の辺と何回交差するかで、内部・外部を判定する。",
  },

  // 最適化・確率的手法
  {
    id: "simulated-annealing",
    name: "焼きなまし法(シミュレーテッド・アニーリング)",
    category: "最適化・確率的手法",
    complexity: "O(問題依存)",
    summary: "温度を下げながら悪化する解も確率的に受け入れ、局所最適から脱出する近似解法。",
  },
  {
    id: "genetic-algorithm",
    name: "遺伝的アルゴリズム",
    category: "最適化・確率的手法",
    complexity: "O(問題依存)",
    summary: "選択・交叉・突然変異を模した確率的探索で、厳密解が難しい問題の近似解を探る。",
  },
  {
    id: "monte-carlo",
    name: "モンテカルロ法",
    category: "最適化・確率的手法",
    complexity: "O(問題依存)",
    summary: "乱数を大量に用いたサンプリングで、解析的に解きにくい問題を確率的に近似する。",
  },
  {
    id: "hill-climbing",
    name: "山登り法(Hill Climbing)",
    category: "最適化・確率的手法",
    complexity: "O(問題依存)",
    summary: "近傍の中で改善する方向にだけ移動し続ける、最も単純な局所探索法。局所最適に陥りやすい。",
  },
  {
    id: "tabu-search",
    name: "タブーサーチ",
    category: "最適化・確率的手法",
    complexity: "O(問題依存)",
    summary: "直近の移動履歴を禁止リストとして持つことで、山登り法が陥る同じ場所への逆戻りを防ぐ。",
  },
  {
    id: "branch-and-bound",
    name: "分枝限定法",
    category: "最適化・確率的手法",
    complexity: "O(問題依存、最悪指数)",
    summary: "解空間を分割しながら、限界値で見込みのない枝を刈り取ることで全探索を高速化する。",
  },
  {
    id: "simplex-method",
    name: "シンプレックス法",
    category: "最適化・確率的手法",
    complexity: "O(問題依存、実用上高速)",
    summary: "線形計画問題の実行可能領域(多面体)の頂点を辿りながら最適解を探す。",
  },

  // 情報検索・ランキング
  {
    id: "bm25",
    name: "BM25(Okapi BM25)",
    category: "情報検索・ランキング",
    complexity: "O(検索語数)",
    summary: "単語の出現頻度と文書長を考慮してクエリとの関連度を採点する、検索エンジンの標準的なランキング関数。",
  },
  {
    id: "tf-idf",
    name: "TF-IDF",
    category: "情報検索・ランキング",
    complexity: "O(語彙数)",
    summary: "単語の出現頻度(TF)と、その単語がどれだけ珍しいか(IDF)を掛け合わせて重要度を数値化する。",
  },
  {
    id: "rrf",
    name: "RRF(Reciprocal Rank Fusion)",
    category: "情報検索・ランキング",
    complexity: "O(kΣ結果数)",
    summary:
      "複数の検索結果(キーワード検索とベクトル検索など)の順位の逆数を足し合わせるだけで、スコアの単位を揃えずに統合できるハイブリッド検索の定番手法。",
  },
  {
    id: "pagerank",
    name: "PageRank",
    category: "情報検索・ランキング",
    complexity: "O(V + E)(反復1回あたり)",
    summary: "「重要なページからリンクされているページは重要」という考えを固有ベクトル計算に落とし込む、Googleの創業技術。",
  },
  {
    id: "hits",
    name: "HITS(Hyperlink-Induced Topic Search)",
    category: "情報検索・ランキング",
    complexity: "O(V + E)(反復1回あたり)",
    summary: "ハブ(良いリンク集)とオーソリティ(良い被リンク先)を相互に強化しながらスコアリングする。",
  },
  {
    id: "minhash-lsh",
    name: "MinHash / LSH(局所性鋭敏型ハッシュ)",
    category: "情報検索・ランキング",
    complexity: "O(1)(近似)",
    summary: "集合の類似度(Jaccard係数)をハッシュの一致率で近似し、大規模データの重複検出を高速化する。",
  },

  // 機械学習
  {
    id: "k-means",
    name: "k-means法",
    category: "機械学習",
    complexity: "O(nkdi)(反復i回)",
    summary: "データ点を最も近い重心のクラスタに割り当て、重心を更新することを繰り返す、最も基本的なクラスタリング手法。",
  },
  {
    id: "knn",
    name: "k近傍法(k-NN)",
    category: "機械学習",
    complexity: "O(nd)(クエリごと)",
    summary: "学習フェーズを持たず、予測時に最も近いk個のデータの多数決/平均で判断する怠惰学習の代表格。",
  },
  {
    id: "decision-tree",
    name: "決定木",
    category: "機械学習",
    complexity: "O(n log n)(構築)",
    summary: "情報利得やジニ不純度が最大になる条件で再帰的にデータを分割する、人間にも読める予測モデル。",
  },
  {
    id: "naive-bayes",
    name: "ナイーブベイズ",
    category: "機械学習",
    complexity: "O(nd)",
    summary: "特徴同士が独立だと(強引に)仮定することで、ベイズの定理による分類を現実的な計算量で実現する。",
  },
  {
    id: "gradient-descent",
    name: "勾配降下法",
    category: "機械学習",
    complexity: "O(反復回数×n)",
    summary: "損失関数の勾配と逆方向にパラメータを更新し続けることで最小値に近づく、機械学習全般を支える最適化の基盤。",
  },
  {
    id: "backpropagation",
    name: "誤差逆伝播法(バックプロパゲーション)",
    category: "機械学習",
    complexity: "O(重み数)(1反復)",
    summary: "出力層の誤差を連鎖律で入力側に伝播させ、ニューラルネットワークの全重みの勾配を効率的に計算する。",
  },
  {
    id: "perceptron",
    name: "パーセプトロン",
    category: "機械学習",
    complexity: "O(nd)(1エポック)",
    summary: "入力の重み付き和が閾値を超えるかで分類する最も単純なニューラルネット。線形分離不可能な問題を解けない限界が後の研究を導いた。",
  },
  {
    id: "random-forest",
    name: "ランダムフォレスト",
    category: "機械学習",
    complexity: "O(m・n log n)(m本の木)",
    summary: "複数の決定木をデータと特徴の両方をランダムに変えて学習し多数決を取ることで、過学習を抑え精度を上げる。",
  },
  {
    id: "svm",
    name: "サポートベクターマシン(SVM)",
    category: "機械学習",
    complexity: "O(n²) 〜 O(n³)(学習)",
    summary: "クラス間のマージンを最大化する境界を求める。カーネルトリックで非線形分離にも対応できる。",
  },
  {
    id: "pca",
    name: "主成分分析(PCA)",
    category: "機械学習",
    complexity: "O(min(n²d, nd²))",
    summary: "データの分散が最大になる方向を新しい軸として、次元を削減しながら情報の損失を最小限に抑える。",
  },

  // デザインパターン(GoF 23種)
  {
    id: "singleton-pattern",
    name: "Singleton(シングルトン)",
    category: "デザインパターン",
    complexity: "生成に関するパターン",
    summary: "インスタンスを1つに制限し、グローバルなアクセス点を提供する。テスト容易性を損ないやすく乱用注意。",
  },
  {
    id: "factory-method-pattern",
    name: "Factory Method(ファクトリーメソッド)",
    category: "デザインパターン",
    complexity: "生成に関するパターン",
    summary: "インスタンス生成をサブクラスに委ねることで、生成ロジックと利用側を分離する。",
  },
  {
    id: "abstract-factory-pattern",
    name: "Abstract Factory(抽象ファクトリー)",
    category: "デザインパターン",
    complexity: "生成に関するパターン",
    summary: "関連するオブジェクト群をまとめて生成するインターフェースを提供し、具体的な実装群を丸ごと差し替え可能にする。",
  },
  {
    id: "builder-pattern",
    name: "Builder(ビルダー)",
    category: "デザインパターン",
    complexity: "生成に関するパターン",
    summary: "複雑なオブジェクトの生成手順を段階的なメソッド呼び出しに分解し、同じ手順から異なる表現を組み立てられるようにする。",
  },
  {
    id: "prototype-pattern",
    name: "Prototype(プロトタイプ)",
    category: "デザインパターン",
    complexity: "生成に関するパターン",
    summary: "既存のインスタンスを複製(クローン)することで、コストの高い生成処理を避ける。",
  },
  {
    id: "adapter-pattern",
    name: "Adapter(アダプター)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "互換性のないインターフェース同士を仲介し、既存クラスを変更せずに新しい文脈で使えるようにする。",
  },
  {
    id: "bridge-pattern",
    name: "Bridge(ブリッジ)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "抽象と実装を別々の継承階層に分離し、両者を独立に拡張できるようにする。",
  },
  {
    id: "composite-pattern",
    name: "Composite(コンポジット)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "個々のオブジェクトとその集合を同じインターフェースで扱い、木構造を再帰的に統一的に処理する。",
  },
  {
    id: "decorator-pattern",
    name: "Decorator(デコレーター)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "オブジェクトを別のオブジェクトで包むことで、継承を使わずに機能を動的に追加する。",
  },
  {
    id: "facade-pattern",
    name: "Facade(ファサード)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "複雑なサブシステム群に対して単純な窓口を1つ提供し、利用側の依存を減らす。",
  },
  {
    id: "flyweight-pattern",
    name: "Flyweight(フライウェイト)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "共有可能な状態を複数のオブジェクトで使い回すことで、大量オブジェクト生成時のメモリ消費を抑える。",
  },
  {
    id: "proxy-pattern",
    name: "Proxy(プロキシ)",
    category: "デザインパターン",
    complexity: "構造に関するパターン",
    summary: "本体への参照を代理オブジェクトが仲介し、遅延生成・アクセス制御・キャッシュなどを透過的に挟み込む。",
  },
  {
    id: "chain-of-responsibility-pattern",
    name: "Chain of Responsibility(責任の連鎖)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "複数のハンドラを鎖状につなぎ、処理できるものが現れるまで順に受け渡していく。",
  },
  {
    id: "command-pattern",
    name: "Command(コマンド)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "操作をオブジェクトとしてカプセル化し、実行の取り消し・キューイング・ログ記録を可能にする。",
  },
  {
    id: "interpreter-pattern",
    name: "Interpreter(インタープリター)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "文法規則をクラス階層として表現し、構文木をたどることで独自のミニ言語を解釈・実行する。",
  },
  {
    id: "iterator-pattern",
    name: "Iterator(イテレーター)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "集合の内部構造を隠したまま、要素へ順番にアクセスする手段を提供する。",
  },
  {
    id: "mediator-pattern",
    name: "Mediator(メディエーター)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "オブジェクト同士を直接やりとりさせず、仲介役に集約することで結合度を下げる。",
  },
  {
    id: "memento-pattern",
    name: "Memento(メメント)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "オブジェクトの内部状態をカプセル化して保存し、カプセル化を破らずに後から復元できるようにする。",
  },
  {
    id: "observer-pattern",
    name: "Observer(オブザーバー)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "状態変化を購読者全員に自動通知する。イベント駆動アーキテクチャの基礎。",
  },
  {
    id: "state-pattern",
    name: "State(ステート)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "オブジェクトの状態ごとの振る舞いを別クラスに分離し、状態遷移をif文の羅列ではなくオブジェクトの差し替えとして表現する。",
  },
  {
    id: "strategy-pattern",
    name: "Strategy(ストラテジー)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "アルゴリズムをインターフェースの背後に隠し、実行時に差し替え可能にする。本サイトのソート切り替えもこの発想に近い。",
  },
  {
    id: "template-method-pattern",
    name: "Template Method(テンプレートメソッド)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "処理の骨格を親クラスに固定し、可変部分だけをサブクラスに実装させる。",
  },
  {
    id: "visitor-pattern",
    name: "Visitor(ビジター)",
    category: "デザインパターン",
    complexity: "振る舞いに関するパターン",
    summary: "データ構造とその上で行う操作を分離し、既存クラスを変更せずに新しい操作を追加できるようにする。",
  },

  // シミュレーション・群知能
  {
    id: "boids",
    name: "Boidsアルゴリズム",
    category: "シミュレーション・群知能",
    complexity: "O(n²)(単純実装)",
    summary: "分離・整列・結合という3つの単純な局所ルールだけから、鳥の群れのような複雑な創発的挙動が生まれる。",
  },
  {
    id: "conways-game-of-life",
    name: "ライフゲーム(Conway's Game of Life)",
    category: "シミュレーション・群知能",
    complexity: "O(セル数)(1世代)",
    summary: "生死2状態と近傍数だけの単純な規則から、グライダーのような自己組織化パターンが生まれるセル・オートマトンの代表例。",
  },
  {
    id: "ant-colony-optimization",
    name: "蟻コロニー最適化(ACO)",
    category: "シミュレーション・群知能",
    complexity: "O(問題依存)",
    summary: "フェロモンの蓄積と蒸発を模した確率的探索で、巡回セールスマン問題などの近似解を集団的に見つける。",
  },
  {
    id: "particle-swarm-optimization",
    name: "粒子群最適化(PSO)",
    category: "シミュレーション・群知能",
    complexity: "O(問題依存)",
    summary: "各粒子が自分のベストと群れ全体のベストに引き寄せられながら探索空間を飛び回る、群知能に基づく最適化手法。",
  },
  {
    id: "langtons-ant",
    name: "ラングトンのアリ",
    category: "シミュレーション・群知能",
    complexity: "O(ステップ数)",
    summary:
      "「白マスなら右折して色を反転、黒マスなら左折して色を反転」という2ルールだけから、無秩序を経てやがて規則的な「道」を作り出す。",
  },

  // 分散システム
  {
    id: "paxos",
    name: "Paxos",
    category: "分散システム",
    complexity: "O(ノード数)(メッセージ数)",
    summary: "一部のノードが故障・遅延しても、分散システム全体で1つの値に合意できることを保証する合意アルゴリズムの原典。",
  },
  {
    id: "raft",
    name: "Raft",
    category: "分散システム",
    complexity: "O(ノード数)(メッセージ数)",
    summary: "リーダー選出とログ複製を分離して理解しやすく設計した合意アルゴリズム。「Paxosより分かりやすい」ことを目標に生まれた。",
  },
  {
    id: "two-phase-commit",
    name: "二相コミット(2PC)",
    category: "分散システム",
    complexity: "O(ノード数)",
    summary: "準備フェーズとコミットフェーズに分けることで分散トランザクションの原子性を保証する。コーディネーター障害に弱い。",
  },
  {
    id: "vector-clocks",
    name: "ベクタークロック",
    category: "分散システム",
    complexity: "O(ノード数)",
    summary: "各ノードが持つカウンタの組で、分散システムにおけるイベントの因果関係(並行も含め)を判定する。",
  },
  {
    id: "consistent-hashing",
    name: "一貫性ハッシュ法",
    category: "分散システム",
    complexity: "O(log n)",
    summary: "ハッシュ空間を環状に扱うことで、ノードの追加・削除時に再配置が必要なデータを最小限に抑える。分散キャッシュやDHTの基礎。",
  },
  {
    id: "bully-algorithm",
    name: "ブリー・アルゴリズム(いじめっ子アルゴリズム)",
    category: "分散システム",
    complexity: "O(n²)(最悪)",
    summary: "ノードIDが最大のものが新リーダーになるまでメッセージをやり取りする、分散システムにおけるリーダー選出の古典的手法。",
  },
];
